Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -8,29 +8,35 @@ on:
 
 jobs:
   build:
-
+    name: CI Build
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v2
+    
     - name: Setup .NET 5.0
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 5.0.x
+    
     - name: Setup .NET Core 2.0
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 2.0.x
+    
     - name: Restore dependencies
       run: dotnet restore
+    
     - name: Build
       run: dotnet build --no-restore
+    
     - name: Test
       run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
+    
+    - name: Upload Test Results
+      uses: actions/upload-artifact@v2  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
       with:
-        name: Dotnet Tests          # Name of the check run which will be created
-        path: Tests/TestResults/test-results.trx      # Path to test results
-        reporter: dotnet-trx        # Format of test results
+        name: test-results
+        path: Tests/TestResults/test-results.trx
+    
